export const LOADER_PHRASES = [
  'Percolating…',
  'Blooming…',
  'Decanting…',
  'Tempering…',
  'Degassing…',
  'Scorching…',
  'Cupping…',
  'Burring…',
  'Beanstalking…',
  'Assaying…',
  'Smelting…',
  'Hoarding…',
  'Gilding…',
  'Fee-fi-fo-fumbling…',
  'Bean-counting…',
  'Spilling the beans…',
  'North-Star-gazing…',
  'Overcaffeinating…',
  'Compounding…',
  'Funneling…',
] as const
