#!/usr/bin/env node
// extract-css.mjs — lift the approved prototype's stylesheet into console-reference.css.
// A builder ports from real CSS, never from a prose description of it.
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = dirname(fileURLToPath(import.meta.url))
const src = readFileSync(join(HERE, 'flags-console-prototype.html'), 'utf8')
const css = /<style>([\s\S]*?)<\/style>/.exec(src)?.[1]?.trim()
if (!css) { console.error('extract-css: no <style> block in the prototype'); process.exit(1) }

writeFileSync(join(HERE, 'console-reference.css'),
`/* console-reference.css — EXTRACTED VERBATIM from flags-console-prototype.html.
 * Do not edit this file. Regenerate: node design/extract-css.mjs
 *
 * Class names here are the PROTOTYPE's, not the app's. Porting means mapping them onto the real
 * markup (.product-shell__*, .console-rail, .data-table). Where the two disagree, the measured
 * table in CONSOLE-CONTRACT.md wins — not these selectors.
 */

${css}
`)
console.log(`console-reference.css — ${css.split('\n').length} lines`)
